#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../lib/collie"

begin
  Collie::CLI.start(ARGV)
rescue Interrupt
  warn "\nInterrupted"
  exit 130
rescue StandardError => e
  warn "Error: #{e.message}"
  warn e.backtrace.join("\n") if ENV["DEBUG"]
  exit 1
end
